### ISSUE TITLE
Words with accents

### ISSUE THREAD

**Issue by hsang** [pablodms/spacy-spanish-lemmatizer#3]
Hi:

First of all thank you for your work, I think it is incredible. I am facing some problems with the lemmatizer, it seems it has some problems with  some words that include accents:

For instance: Lemmas of '**realizó** realiza quiero **quería**' are '**realizó** realizar querer **quería**'

Am I doing something wrong?

Best regards,
hsang

**Comment by pablodms** [comment]
Thank you very much, @hsang 

I think your problem is due to the sentence structure and not the accents. The POS tagger would not have probably tagged the words **realizó** and **quería** as verbs, so lemmatization rules for verbs are not applied.

Have you tried lemmatization in a well-structured sentence? For example:
"El profesor quería captar la atención de los alumnos y les realizó una pregunta."

I think if POS tagger tags **realizó** and **quería** as VERB they will be properly lemmatized.  You can access the POS tag through *pos_* property of the token. At https://spacy.io/usage/linguistic-features you can see a code snippet where POS tags are retrieved.

Best regards,
Pablo

**Comment by hsang** [comment]
Hi Pablo,

Thank you for your fast reply and for the link. Unfortunately it is still not working:

_Antonio antonio PROPN 
**realizó realizó VERB** 
un uno DET 
comentario comentario NOUN 
. . PUNCT 
No no ADV 
**quería quería VERB**
contrariar contrariar VERB
a a ADP 
nadie nadie PRON_

I guess I can try to use stemmers in order to solve these problems.

Best regards,
Hugo

**Comment by lmorillas** [comment]
Curious. 

```
import spacy
from spacy_spanish_lemmatizer import SpacyCustomLemmatizer

# generic spacy
nlp = spacy.load("es_core_news_sm")

# spanish lemmatizer
nlp_sp = spacy.load("es_core_news_sm")
lemmatizer = SpacyCustomLemmatizer()
nlp_sp.add_pipe(lemmatizer, name="lemmatizer", after="tagger")

frase = 'Él quería caminar por la mañana'

for token in nlp(frase):
    print(token.text, token.lemma_, token.pos_)


for token in nlp_sp(frase):
    print(token.text, token.lemma_, token.pos_)
```
Gives the following results:

For generic nlp
```
Él Él PRON
quería querer VERB
caminar caminar VERB
por por ADP
la lo DET
mañana mañana NOUN
```
With **spanish lemmatizer**
```
Él él PRON
quería quer VERB
caminar caminar VERB
por por ADP
la el DET
mañana mañana NOUN
```

**Comment by hsang** [comment]
Thank you very much  Pablo. It is working now. It seems I was using different lemmatizers and I employed the same variable name for them. Sorry for this misunderstanding and thank you again for your help.

Best wishes,
Hugo

**Comment by lmorillas** [comment]
Why closed? I think that it's not working properly :-/

**Comment by hsang** [comment]
Sorry, that´s true, it is not working at all. At least it returns something different with the words with accents, which was my initial query :S Regarding **quer** lemma. Any ideas?

**Comment by pablodms** [comment]
Hello @lmorillas 

I have tried to run your code:

```
import spacy
from spacy_spanish_lemmatizer import SpacyCustomLemmatizer

# generic spacy
nlp = spacy.load("es_core_news_sm")

# spanish lemmatizer
nlp_sp = spacy.load("es_core_news_sm")
lemmatizer = SpacyCustomLemmatizer()
nlp_sp.add_pipe(lemmatizer, name="lemmatizer", after="tagger")

frase = 'Él quería caminar por la mañana'

print ("\n#### GENERIC")

for token in nlp(frase):
    print(token.text, token.lemma_, token.pos_)

print("\n#### CUSTOM")

for token in nlp_sp(frase):
    print(token.text, token.lemma_, token.pos_)
```
It gives me the following:

```
#### GENERIC
Él Él PRON
quería querer VERB
caminar caminar VERB
por por ADP
la lo DET
mañana mañana NOUN

#### CUSTOM
Él él PRON
quería querer VERB
caminar caminar VERB
por por ADP
la el DET
mañana mañana NOUN
```
As you can see, in my case, the output is correct. I am not sure what problem is causing the differences. I am currently using the Github version and not the one uploaded to pip. Could you give more details?

**Comment by hsang** [comment]
It is working ok on my version too :S I installed it again after uninstalling other packages that I tried before.

**Comment by pablodms** [comment]
I close this issue as there have been no errors recently.

Thank you very much for your contributions.
