### ISSUE TITLE
Would the NER use the lemmatizer component?

### ISSUE THREAD

**Issue by fcggamou** [pablodms/spacy-spanish-lemmatizer#6]
Hi,

Thanks for the great work. Sorry if this is an obvious question. If I add this custom component to my spacy model and then train the NER component, would it be using the lemmatizer automatically or should I manually execute the lemmatizer e.g. over my training data before training my NER?

Thanks!

**Comment by pablodms** [comment]
Hi @fcggamou,

Glad you like the lemmatizer. 

I have never tried to train a NER component, but as far as I know, the lemmatizer is an independent stage and therefore I think it should not be used before [training the NER](https://spacy.io/usage/training). On the reference page, spaCy uses raw text (not lemmatized) as input in the "Training with annotations" section.

I hope it helps you.

**Comment by fcggamou** [comment]
Thank you Pablo, I will experiment with this.
