### ISSUE TITLE
OSError: [E050] Can't find model 'es'

### ISSUE THREAD

**Issue by VicenteLawal** [pablodms/spacy-spanish-lemmatizer#7]
Hello Pablo,

many thanks for this spanish rule based lemmatizer. I followed your instructions:

pip install spacy_spanish_lemmatizer
python -m spacy_spanish_lemmatizer download wiki

When I try to use it in jupyter notebook, I get the following error:

"OSError: [E050] Can't find model 'es'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory."

Any idea what might be the problem? Sorry for the basic question...

I use the exact example you published:

import spacy
from spacy_spanish_lemmatizer import SpacyCustomLemmatizer

nlp = spacy.load("es")
lemmatizer = SpacyCustomLemmatizer()
nlp.add_pipe(lemmatizer, name="lemmatizer", after="tagger")
for token in nlp(
    """Con estos fines, la Dirección de Gestión y Control Financiero monitorea
       la posición de capital del Banco y utiliza los mecanismos para hacer un
       eficiente manejo del capital."""
):
    print(token.text, token.lemma_)

**Comment by hsarmiento** [comment]
Hi Vicente,

I had the same problem, but I solved doing the following steps:

In addition to download and install the spanish_lemmatizer, you need to download the pretrained statistical models for Spanish available on https://spacy.io/models/es

Considering your size option (sm, md or lg), you should install one of these (e.g., python -m spacy download es_core_news_md) and replace the model name on the spacy.load

For example, if you downloaded the medium size, you code looks like this:

nlp = spacy.load("es_core_news_md")

The rest of the code, is the same. The  full new code is the following for me:

import spacy
from spacy_spanish_lemmatizer import SpacyCustomLemmatizer
nlp = spacy.load("es_core_news_md")
lemmatizer = SpacyCustomLemmatizer()
nlp.add_pipe(lemmatizer, name="lemmatizer", after="tagger")
for token in nlp(
    """Con estos fines, la Dirección de Gestión y Control Financiero monitorea
       la posición de capital del Banco y utiliza los mecanismos para hacer un
       eficiente manejo del capital."""
):
    print(token.text, token.lemma_)

**Comment by pablodms** [comment]
Hello all,

I think @hsarmiento  is right, I will update the README.md accordingly to avoid confusion.
